remote_theme: "mmistakes/minimal-mistakes"
title: "skankingpigeon"
description: "Github Page"

folder_links:
  - title: "📂 Code Snippets"
    url: "https://github.com/skankingpigeon/skankingpigeon.github.io/tree/main/Code/"
    order: 1
  - title: "📂 Repo Home"
    url: "https://github.com/skankingpigeon/skankingpigeon.github.io"
    order: 2